/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;

/**
 *
 * @author Asus
 */
public class property_image_show extends javax.swing.JFrame {

    /**
     * Creates new form property_image_show
     */
    static int propertyid;
    ArrayList<byte[]>imageList;
    int index=0;
    public property_image_show(int imageid) {
        initComponents();
        this.propertyid=imageid;
           Border imgaeborder=BorderFactory.createMatteBorder(1, 1, 2, 1,new Color(0,0,0));
        txtimages.setBorder(imgaeborder);
         Border nextborder=BorderFactory.createMatteBorder(2, 2, 2, 2,new Color(0,255,0));
        txtnext.setBorder(nextborder);
        txtback.setBorder(nextborder);
        
        HashMap<byte[],Integer>map=new p_property().propertieimagelist(propertyid);
        imageList=new ArrayList<>(map.keySet());
        displayImage(index);
    }
    public void displayImage(int index){
           
          Image img=new ImageIcon(imageList.get(index)).getImage().getScaledInstance(txtimages.getWidth(),txtimages.getHeight(), Image.SCALE_SMOOTH);
          ImageIcon image=new ImageIcon(img);
          txtimages.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtimages = new javax.swing.JLabel();
        txtback = new javax.swing.JLabel();
        txtnext = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtimages.setBackground(new java.awt.Color(204, 255, 255));
        txtimages.setOpaque(true);

        txtback.setBackground(new java.awt.Color(255, 255, 255));
        txtback.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtback.setText("<");
        txtback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtbackMouseExited(evt);
            }
        });

        txtnext.setBackground(new java.awt.Color(255, 255, 255));
        txtnext.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtnext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnext.setText(">");
        txtnext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtnext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtnextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtnextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtback, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtnext, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtimages, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtimages, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtback, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnext, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnextMouseClicked
        // TODO add your handling code here:
        index++;
        if(index>=imageList.size()){
            index=imageList.size()-1;
            displayImage(index);
        }
    }//GEN-LAST:event_txtnextMouseClicked

    private void txtbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbackMouseClicked
        // TODO add your handling code here:
        index--;
        if(index<0){
            index=0;
            displayImage(index);
        }
    }//GEN-LAST:event_txtbackMouseClicked

    private void txtnextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnextMouseEntered
       txtnext.setBackground(Color.black);
       txtnext.setForeground(Color.white);
    }//GEN-LAST:event_txtnextMouseEntered

    private void txtnextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnextMouseExited
       txtnext.setBackground(Color.white);
       txtnext.setForeground(Color.black);
    }//GEN-LAST:event_txtnextMouseExited

    private void txtbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbackMouseEntered
        // TODO add your handling code here:
        txtback.setBackground(new Color(255,69,0));
       txtback.setForeground(Color.red);
    }//GEN-LAST:event_txtbackMouseEntered

    private void txtbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbackMouseExited
        // TODO add your handling code here:
         txtback.setBackground(Color.white);
       txtback.setForeground(Color.black);
    }//GEN-LAST:event_txtbackMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(property_image_show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(property_image_show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(property_image_show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(property_image_show.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new property_image_show(propertyid).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtback;
    private javax.swing.JLabel txtimages;
    private javax.swing.JLabel txtnext;
    // End of variables declaration//GEN-END:variables
}
